#!/bin/bash
cat 編集用ファイル/責任担当水研等.tex > output/sekinintantou.tex
cat 編集用ファイル/要約.tex > output/youyaku.tex
cat 編集用ファイル/まえがき.tex > output/maegaki.tex
cat 編集用ファイル/要約_管理基準の表.tex > output/youyaku_table.tex
cat 編集用ファイル/分布・回遊.tex > output/bunpu_kaiyu.tex
cat 編集用ファイル/年齢・成長.tex > output/nenrei_seichou.tex
cat 編集用ファイル/成熟・産卵.tex > output/seijuku_sanran.tex
cat 編集用ファイル/被捕食関係.tex > output/hihoshokukankei.tex
cat 編集用ファイル/漁業の概要.tex > output/gyogyou_gaiyou.tex
cat 編集用ファイル/漁獲量の推移.tex > output/gyokakuryou_suii.tex
cat 編集用ファイル/資源評価の方法.tex > output/shigenhyouka_houhou.tex
cat 編集用ファイル/資源量指標値の推移.tex > output/shigenryou_shihyouchi.tex
cat 編集用ファイル/漁獲物の年齢組成.tex > output/gyokakubutsu_nenreisosei.tex
cat 編集用ファイル/資源量と漁獲割合の推移.tex > output/shigenryou_gyokakuwariai.tex
cat 編集用ファイル/Blimitの設定.tex > output/blimit_settei.tex
cat 編集用ファイル/資源の水準・動向.tex > output/shigen_suijun_doukou.tex
cat 編集用ファイル/資源と漁獲の関係.tex > output/shigen_gyokaku.tex
cat 編集用ファイル/資源評価のまとめ.tex > output/shigenhyouka_matome.tex
cat 編集用ファイル/ABCの算定.tex > output/abc_santei.tex
cat 編集用ファイル/ABCの評価.tex > output/abc_hyouka.tex
cat 編集用ファイル/ABCの再評価.tex > output/abc_saihyouka.tex
cat 編集用ファイル/ABC以外の管理方策の提言.tex > output/abc_igai_no_kanrihousaku.tex
cat 編集用ファイル/図.tex > output/figures.tex
cat 編集用ファイル/引用文献.bib > output/references.bib
